### ISSUE TITLE
"Why Linux is better" should be linked to root of website, not the domain

### ISSUE THREAD

**Issue by theel0ja** [iamunknown2/whylinuxisbetter#1]
Screenshot of it:

![screenshot_2017-04-29-09-55-19](https://cloud.githubusercontent.com/assets/5832930/25553671/ff2efb68-2cc1-11e7-9cfd-7d0a050b3504.png)

**Comment by iamunknown2** [comment]
Ah yes.

**Comment by theel0ja** [comment]
Fixed by https://github.com/iamunknown2/whylinuxisbetter/commit/65977061e81285da975f6a9cfc88e3b8bd636d51
