### ISSUE TITLE
Use master for GitHub Pages instead of gh-pages

### ISSUE THREAD

**Issue by theel0ja** [iamunknown2/whylinuxisbetter#3]
I don't see any reason to use 2 similar branches.

![image](https://cloud.githubusercontent.com/assets/5832930/25555853/a9ea7c6c-2cf9-11e7-9803-182f3d2271c7.png)

**Comment by iamunknown2** [comment]
Huh, good point - really, the only reasons (which is pretty flimsy) which I used two instead of one was: 1) I forgot you could do that :P and 2) the baseurl had to be different (which isn't much of a problem now).

**Comment by iamunknown2** [comment]
Closing - fixed (gh-pages is now deleted as well).
